-- PARA PASE
ALTER TABLE sirade.srd_jci_encuestas CHANGE ESTADO_REG NAUDI_EST_REG INT;
ALTER TABLE sirade.SRD_JCI_CATEGORIA_PREG CHANGE ESTADO_REG NAUDI_EST_REG INT;
ALTER TABLE sirade.srd_jci_encuestas 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(); 
ALTER TABLE sirade.srd_jci_encuestas_preg 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(); 
ALTER TABLE sirade.srd_jci_areas_super 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP();

CREATE TABLE `srd_horas_extras` (
  `NHOEX_ID` int NOT NULL AUTO_INCREMENT,
  `CTURN_ID` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CAREA_ID` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CHOEX_CODIGO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DHOEX_FECHA_INICIAL` date DEFAULT NULL,
  `DHOEX_FECHA_FINAL` date DEFAULT NULL,
  `NAUDI_REG_INS` int NOT NULL COMMENT 'AUDITORIA: USUARIO DE REGISTRO',
  `DAUDI_REG_INS` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'AUDITORIA: FECHA DE REGISTRO',
  `NAUDI_REG_UPD` int DEFAULT NULL COMMENT 'AUDITORIA: USUARIO DE ACTUALIZACIÓN',
  `DAUDI_REG_UPD` datetime DEFAULT NULL COMMENT 'AUDITORIA: FECHA DE ACTUALIZACIÓN',
  `NAUDI_EST_REG` int NOT NULL DEFAULT '1' COMMENT 'AUDITORIA: ESTADO DE REGISTRO (1=ACTIVO, 0=INACTIVO)',
  `NHOEX_ESTADO` int NOT NULL DEFAULT '1' COMMENT 'ESTADO DE REGISTRO (1=ACTIVO, 0=INACTIVO)',
  PRIMARY KEY (`NHOEX_ID`),
  KEY `srd_horas_extras_srd_areas_fk` (`CAREA_ID`),
  KEY `srd_horas_extras_srd_turno_fk` (`CTURN_ID`),
  CONSTRAINT `srd_horas_extras_srd_areas_fk` FOREIGN KEY (`CAREA_ID`) REFERENCES `srd_areas` (`CAREA_ID`) ON UPDATE CASCADE,
  CONSTRAINT `srd_horas_extras_srd_turno_fk` FOREIGN KEY (`CTURN_ID`) REFERENCES `srd_turno` (`CTURN_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

UPDATE sirade.srd_aplicaciones SET NAUDI_EST_REG = 0 WHERE CAPLI_ID = 'ENF_001' ;

COMMIT;