-- PARA PASE
ALTER TABLE sirade.srd_jci_encuestas CHANGE ESTADO_REG NAUDI_EST_REG INT;
ALTER TABLE sirade.SRD_JCI_CATEGORIA_PREG CHANGE ESTADO_REG NAUDI_EST_REG INT;
ALTER TABLE sirade.srd_jci_encuestas 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(); 
ALTER TABLE sirade.srd_jci_encuestas_preg 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(); 
ALTER TABLE sirade.srd_jci_areas_super 
	CHANGE NUSUA_REG_UPD NAUDI_REG_UPD INT,
	CHANGE DUSUA_REG_UPD DAUDI_REG_UPD DATETIME,
	CHANGE NUSUA_REG_INS NAUDI_REG_INS INT NOT NULL,
	CHANGE DUSUA_REG_INS DAUDI_REG_INS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP();